# Generated by Django 4.2.4 on 2023-10-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertopalbums",
            name="album",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="usertopartists",
            name="artist",
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name="Album",
        ),
        migrations.DeleteModel(
            name="Artist",
        ),
    ]
