# Generated by Django 4.2.4 on 2023-10-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Dashboard", "0003_usertoptracks_delete_usertopalbums"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertopartists",
            name="image",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usertoptracks",
            name="image",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
