# Generated by Django 4.2.4 on 2023-10-09 01:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Dashboard", "0004_usertopartists_image_usertoptracks_image"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usertopartists",
            unique_together={("user_id", "artist", "image", "rank")},
        ),
        migrations.AlterUniqueTogether(
            name="usertoptracks",
            unique_together={("user_id", "track", "image", "rank")},
        ),
    ]
